### ISSUE TITLE
Create a registration form

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/BarCamp2024#1]
We need to make a registration form, for people to let us know they want to come and optionally to request travel funding.

Once we agree on the fields, the form can be hosted on https://www.limesurvey.org/, for which we have an account.

Here is a draft.

## Form

Use this form to register for attendance of the BarCamp, both on-site and remotely.

* **Name:** _(small text input)_
* **Email address:** _(small text input)_
* **OpenRefine forum username** (optional): _(small text input)_
* **GitHub username** (optional): _(small text input)_
* **Describe in a few words your relation to OpenRefine. Where does your interest in the BarCamp come from?** _(larger text area, limited to a few hundred characters)_
* **What topics and activities are you hoping to see at the BarCamp?** _(larger text area, limited to a few hundred characters)_
* **I plan to attend**: _(radio buttons)_
     * on site
     * remotely
* **Any dietary restrictions?** _(text area)_
* **Is there anything else organizers should be aware of (such as special needs and wishes)?** _(text area)_
* _(required checkbox)_  **I have read and agree to follow the friendly space policy** (#8)

Only shown if attending onsite:
* _(checkbox)_  **I request financial support towards my travel costs**

Only shown if financial support is requested:
* **Where will you be traveling from?** _(small text input)_
* **Estimate the cost of your journey (return trip) in USD:** _(number input)_

**Comment by ayushrai206** [comment]
@wetneb, I think I can do this.

**Comment by ayushrai206** [comment]
Maybe, we can also add the option of if they want to give a talk and add the link of "proposal for session" in the form, but we might need to edit this option when no. of slots for the talk are filled.

**Comment by wetneb** [comment]
To propose sessions, I would use a dedicated platform (see #3). We can mention it in the form with a link to the session submission, but I wouldn't try to integrate it into the same form (people should be able to propose multiple sessions and vote on others' proposals).

Given #6 I think it would be useful to extend the form to cover remote attendees too, so that we have an idea of the numbers. I have updated the draft accordingly.

**Comment by magdmartin** [comment]
I am not keen on using SurveyMonkey for the registration since we are not running a survey. I would prefer something integrated with the platform, like  https://barcamps.eu/  or a Google Form so multiple people can access the results via Google Drive.

**Comment by wetneb** [comment]
It makes sense to use barcamps.eu indeed, it's all integrated. I have started setting up the form there. I simplified a bit, removing the question about the GitHub username (forum should be enough) and the question about topics (people can propose sessions already, and it's redundant with the previous question).

I am not sure about asking for travel details there or in a separate form…

@ayushrai206 I've invited you to the platform so you can make further tweaks

**Comment by magdmartin** [comment]
I would ask about the travel details in the same form so it only one form to fill and we will have an idea early one how many people are asking and an approximate $ amount.

**Comment by ayushrai206** [comment]
> I would ask about the travel details in the same form so it only one form to fill and we will have an idea early one how many people are asking and an approximate $ amount.

Yes, seconded!

**Comment by wetneb** [comment]
@ayushrai206 you are now an organizer on barcamps.eu and you should be able to make changes to the registration form (feel free to delete all the fields and start again if needed):
https://barcamps.eu/openrefine-2024-barcamp/registration_editor

Could you finalize it so that we can open registration?

**Comment by ayushrai206** [comment]
sureee!

**Comment by ayushrai206** [comment]
Hey @wetneb, 

1)Where do we add the friendly space policy or the link to it ?
2) I think we do not have the feature of displaying questions only when one an option is selected so I am adding the last questions (about the travel cost etc)with appropriate description

**Comment by ayushrai206** [comment]
Hey @wetneb, where do we add the friendly space policy or the link to it ?

**Comment by wetneb** [comment]
I think barcamps.eu has an integrated feature to show a friendly space policy so I suspect it might already be included in the form as a default. We can check this by opening registration and going through the form ourselves.

**Comment by ayushrai206** [comment]
> I think barcamps.eu has an integrated feature to show a friendly space policy so I suspect it might already be included in the form as a default. We can check this by opening registration and going through the form ourselves.

I opened the registration form just to check and I could not find the friendly space policy, also I am unable to close the registration now :-(

**Comment by wetneb** [comment]
I have disabled registration by making the barcamp private and then making it public again, on this page:
https://barcamps.eu/openrefine-2024-barcamp/admin/wizard
The friendly space policy might need configuring in another page in the administration area: you could try adding a placeholder for now.

**Comment by magdmartin** [comment]
@ayushrai206 @wetneb After checking, I don't think BarCamp.eu offers a friendly-space policy by default. We can add it under `custom pages`

I open this [Google Document](https://docs.google.com/document/d/1002LuRHnn62HFJqisoNOWQDzkP5lxhOWAYetuXbV68g/edit?usp=sharing) to review the text for the different fields when setting up the event. I think it would be easier to track edit and comment in a shared doc than in the platform directly. 

What prevent us from opening the registration?

**Comment by wetneb** [comment]
> What prevent us from opening the registration?

The presence of the friendly space policy - since we ask people to agree it in the form. I have just published it and have turned registration on.

@ayushrai206 @magdmartin can you try registering and check that nothing looks off, before we advertise it more widely?

**Comment by magdmartin** [comment]
@wetneb  I was able to register successfully. Some questions and remarks 
* Why are we using the waiting list, Shouldn't people be able to register directly? 
*  BarCamps.eu manages each day as a separate registration. As a result, I received three similar confirmation emails regarding the pre-registration, and I will receive three emails when my registration is approved for each day. 
* As an admin, we will need to manually approve each member for each day from the [event listing page](https://barcamps.eu/openrefine-2024-barcamp/admin/events) - it took me some time to find the page

**Comment by wetneb** [comment]
> Why are we using the waiting list, Shouldn't people be able to register directly?

I thought we wanted to be able to filter out people who have nothing to do with the project… I have no idea what sort of "spam" level we should expect.
Also, even if we only get legitimate registrations, it *can* be that we exceed capacity, in which case first-come-first-served is perhaps not the best policy… I don't know!
Maybe it's all overly complicated and we should just let people register directly.

> BarCamps.eu manages each day as a separate registration. As a result, I received three similar confirmation emails regarding the pre-registration, and I will receive three emails when my registration is approved for each day.

Yes it's not ideal, I have no idea if we can merge the emails. Intuitively it's still useful that people can sign up for only some of the days, if they are not available the full time.

**Comment by ayushrai206** [comment]
> > Why are we using the waiting list, Shouldn't people be able to register directly?
> 
> I thought we wanted to be able to filter out people who have nothing to do with the project… I have no idea what sort of "spam" level we should expect. Also, even if we only get legitimate registrations, it _can_ be that we exceed capacity, in which case first-come-first-served is perhaps not the best policy… I don't know! Maybe it's all overly complicated and we should just let people register directly.
> 
> > BarCamps.eu manages each day as a separate registration. As a result, I received three similar confirmation emails regarding the pre-registration, and I will receive three emails when my registration is approved for each day.
> 
> Yes it's not ideal, I have no idea if we can merge the emails. Intuitively it's still useful that people can sign up for only some of the days, if they are not available the full time.

I registered smoothly.Also, since we are not doing first come first serve here, it would be good if people are not registering directly.

**Comment by ayushrai206** [comment]
Also, should we put contacts of atleast one extra person out there just in case someone needs to report a violation of FSP and @wetneb is busy?(Just for backup as it could be a serious matter)

**Comment by wetneb** [comment]
yes for sure let's have a team for that :)

**Comment by magdmartin** [comment]
The registration form is live here https://barcamps.eu/openrefine-2024-barcamp/
