### ISSUE TITLE
Prepare volunteer task descriptions and sign-up sheet

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/BarCamp2024#11]
During the event we'll need volunteers to take care of various things to make sure the event runs well. On the first day I would like to present the different tasks involved and let people sign up for shifts on a board. People would sign up for a task for a particular session.

## The stream-sitter

They are the on-site ambassador of remote participants, making sure they are able to participate.

They need to join the Zoom meeting via their own laptop and be given Host permissions. During the session, their task is to:
* make sure interventions (raised hands, comments in the chat) from the remote participants are brought to the attention of the in-person participants
* mute and un-mute Zoom participants as needed (in case they don't do it themselves properly)
* tweaking video settings via the remote control of the meeting capsule, depending on what's happening in the session (switching between different video modes to take the best fit)

## The note-taker

They are the notary of the collective wisdom that will emerge from this gathering!

They take notes about what is being said in the Etherpad associated to the session. They need to do that from their own device.
Joining the Zoom call (without audio or video) could likely be useful as well to access the Zoom chat and copy/paste content between there and the pad.

Other participants also have access to the pad and are able to contribute to the notes.

## The facilitator

They provide the frame for the meeting, setting its scope and defining how people are expected to participate. Is it a presentation made by a single person with questions at the end? Is it a brainstorming session where the participants split out in small groups and then report a summary to the bigger group? Is it a [user experience fishbowl](https://www.sessionlab.com/methods/user-experience-fishbowl)? Or all sorts of other formats, for instance from this [list of facilitation techniques](https://www.sessionlab.com/library). The format should be made clear at the beginning of the meeting to set expectations.

Their main goal is to make sure the session stays on track and that participants get something insightful out of it.

The chosen format should be accessible both for in-person and online participants. For instance, if a session involves participants writing collectively on a whiteboard, consider using an online whiteboard that each participant accesses via their own device.

## Any other?

**Comment by thadguidry** [comment]
Since I'm remote and will be mostly in the background, I can volunteer to help with note taking.  Generally, I'll be the one adding reference links to notes taken by the primary note taker (linking appropriate Issues, Forum posts, web site links).  I'm more interested in listening for the 3 days since I think I've been vocal enough over the years and most of the community knows or has read where I stand on various topics... so, I'll help with note taking.

**Comment by magdmartin** [comment]
@thadguidry, we plan to assign a volunteer role on Monday while doing the scheduling.

**Comment by wetneb** [comment]
This will be done on Monday. The sign up sheet will be the pad where we schedule the sessions.
