### ISSUE TITLE
Gather furniture / accessories required for sessions

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/BarCamp2024#12]
Depending on the sorts of sessions we plan to do, it might be useful to have some accessories available onsite (pens, post-it, stickers…) The venue provides a flipchart.
- [ ] ask session proposers if they foresee needing anything in particular
- [ ] check with the venue to see if they already provide any of it
- [ ] buy the rest and bring it onsite

**Comment by wetneb** [comment]
We need thinks that can serve as badges (name tags).

**Comment by jfaurelacroix** [comment]
We should find a platform like Miro for brainstorming sessions that has a mobile app in case not everyone comes with a laptop.

- https://miro.com/apps/
- https://www.lucidchart.com/pages/lucidchart-for-android : doesn't look like you have all the features on the mobile app

**Comment by magdmartin** [comment]
Should we also plan to use a separate tripod for a phone? This will allow us to capture a still image of a physical board and share it separately from the video via Zoom.

**Comment by magdmartin** [comment]
After discussing with @wetneb and @ayushrai206, we have decided to default to using a virtual board in Miro. This will ensure an equal footing for remote participants and allow us to preserve the notes, as we can create new boards or export them, rather than erasing a physical board. So no need for a tripod to film the board.

**Comment by wetneb** [comment]
With our reliance on online platforms we don't foresee needing much physical furniture. I have a bunch of lanyards and cardboard to do improvised name tags if we want.
