### ISSUE TITLE
Create a list of people/communities to reach out to

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/BarCamp2024#2]
We need to reach out broadly to let people know about this event, to cover:
* various user communities (librarians, researchers, Wikimedians…)
* various types of contributions to the project (developers, translators, trainers…)
* various geographical areas & languages

It would be good to keep track of this communication so that we don't duplicate efforts and aim for a reasonable completeness.

Maybe @magdmartin can help there?

**Comment by magdmartin** [comment]
I can help here. However, since we are talking about personal information, I recommend not to track and share this publicly.

**Comment by wetneb** [comment]
@magdmartin I agree the list shouldn't be public. Could you share this list with me so that I can email people when we open the registration phase?
