### ISSUE TITLE
Prepare video set-up for remote attendance

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/BarCamp2024#6]
We want to make it possible for people to attend remotely.
We need to:
- [ ] decide on a platform to stream the sessions and let people participate remotely.
- [ ] We need to document what hardware that requires on-site and source it locally (a few laptops / webcams dedicated to that might be enough)

I would propose that we always have one person in each session responsible for keeping the stream up and making sure remote attendants can be heard (relaying their questions).

**Comment by Ainali** [comment]
One huge deciding factor for this is how interactive we would like the remote attendance experience to be. Do we just want to broadcast, be able to interact via a chat, or even be able to discuss with audio/video?

**Comment by wetneb** [comment]
Intuitively I'd expect that some key people will not be able to be onsite, so I would be a bit reluctant to let them only participate via a text chat.

I would aim to make it possible for an online participant to intervene with audio/video (perhaps by requesting to be unmuted by the on-site facilitator).

Ideally, I'd also aim to make it possible for remote participants to propose sessions (and so to facilitate them), but maybe that's too ambitious?

**Comment by Ainali** [comment]
I am sorry for my disambiguity. In all my suggestions, a video feed **to** the participant was assumed, as well as that no one of the viewers would be onsite. My questions were more about how much information they could give back to the people in the room. (I have seen plenty of conferences where the remote participants are only audience, with no way to interact with the room.)

If we want them to be able to intervene through audio/video (which I like as it would be an ambitious and inclusive option) then besides using Jitsi or BigBlueButton (or similar platform), we also need to make sure we bring a decent loudspeaker so that people in the room can hear them properly and possibly also a second large screen if we want them to be seen.

Remote facilitation does indeed seem very ambitious and is also hard as it still requires an enforcing in-room co-facilitator. I have been a remote presenter without that, and it was a bit chaotic.

**Comment by tfmorris** [comment]
Running a successful hybrid event is a significant challenge. It requires
not only the technical infrastructure, but the cultural understanding of
what's required (no speaking without the microphone, etc), but also
discipline and manpower (microphone runners, chat question relayers, etc).
Most of this applies even if you just simply want a good video recording,
perhaps with remote Q&A. Doing something like a hybrid panel discussion
would raise the challenge to a whole 'nother level.

It's always been the case that choosing a multi-day, in-person format was
going to significantly privilege those who work full time on OpenRefine and
are located in or around the host city/state/region. I think it's best to
just acknowledge that the segments of the community which don't fit that
profile will be mostly excluded.

Tom

**Comment by wetneb** [comment]
> I am sorry for my disambiguity. In all my suggestions, a video feed to the participant was assumed, as well as that no one of the viewers would be onsite.

@Ainali Yes that's also what I understood, your post did not feel ambiguous to me - so it looks like mine was :)

> It's always been the case that choosing a multi-day, in-person format was going to significantly privilege those who work full time on OpenRefine and are located in or around the host city/state/region.  I think it's best to just acknowledge that the segments of the community which don't fit that profile will be mostly excluded

@tfmorris I agree with you that it's difficult to run a hybrid event, but I think it's worth trying. To me, it is important to make sure as many people as possible can participate.

It might also be easier to decide on the online format once we have a clearer picture of who plans to attend. Maybe it'd be worth having a registration form (#1) for online attendees too, so that we can gauge the interest better.

**Comment by wetneb** [comment]
We're looking into the video/sound set up and weighing in multiple options:
* getting a company to do it (such as https://konferenztechnik.de/en/rent-event-technology/) - probably quite expensive and likely overkill for about 15 on-site participants I would say
* buying or renting specialized equipment (such as one of those https://www.digitalcameraworld.com/buying-guides/best-conference-webcam) - which would be my preference

I propose that for each session we find a person who's responsible for relaying contributions from online participants into the room and making sure the video streaming is working properly.

**Comment by tfmorris** [comment]
I agree that hiring an A/V company is overkill and a waste of money. As I mentioned in my note from a few months ago, a significant piece of this is social/cultural, not technical.

I've used several of the cameras reviewed and I'm not sure they're needed/appropriate either. At least the top rated ones are for 2-3 people around a conference table, not a speaker talking to a room full of people. Video isn't the most important part anyway - audio is. Good lav mikes for the speakers, good handheld mikes for the question askers, good speakers (maybe?) to be able to hear the remote speakers are all ahead of fancy video cameras.

None of this will matter, though, if you tell people "please wait for the microphone before asking your question" and they don't (or tell the speakers, "please repeat the question" and they don't).

And, to repeat my earlier statement, you should accept the fact that you're marginalizing those who don't meet your preferred demographic.

**Comment by Ainali** [comment]
> And, to repeat my earlier statement, you should accept the fact that you're marginalizing those who don't meet your preferred demographic.

I don't quite understand what you point you are trying to get across. Do you mean that since it is not possible to give remote attendees an equal experience to those at the venue, we should not bother to try to include them as much as we can? Or do you mean that we should be aware of that it is not possible to give remote attendees an equal experience however hard we try, and while we should do what we can we should make a public statement that shows that we know it is not the same? Or do you mean something else?

**Comment by tfmorris** [comment]
On Fri, May 3, 2024 at 6:09 AM Jan Ainali ***@***.***> wrote:

> And, to repeat my earlier statement, you should accept the fact that
> you're marginalizing those who don't meet your preferred demographic.
>
> I don't quite understand what you point you are trying to get across. Do
> you mean that since it is not possible to give remote attendees an equal
> experience to those at the venue, we should not bother to try to include
> them as much as we can? Or do you mean that we should be aware of that it
> is not possible to give remote attendees an equal experience however hard
> we try, we should do what we can but make a public statement that shows
> that we know it is not the same? Or do you mean something else?
>
I think a mindset which is key to avoid is the assumption that all the
diverse representative and interested parties are present and equally able
to advocate their positions. It would be easy to fall into the trap of
believing that this is a "global summit" where everyone is equally
represented, which, of course, won't be the case.

We should strive to make remote participation as inclusive as possible, but
it will always be a much less rich and impactful experience for remote
participants. We should continue to use the mailing list for key
discussions and decisions and not assume that everyone has the privilege to
meet face-to-face.

Best,
Tom

**Comment by Ainali** [comment]
Ok, then I think I understand, and I agree that it is important to not fall into such a trap. (I don't agree with you about the mailing list, though, but that is kind of off-topic for this issue.)

**Comment by wetneb** [comment]
We're considering using Zoom for the video call, because CS&S has a Zoom account we can use and it offers breakout sessions and other useful features.

We anticipate that only the main room of the event would be accessible online. The other physical room would be available for in-person attendees who want to do something else during a given session. We could have a similar remote breakout room for online participants who want to chat separately from the main session.

**Comment by wetneb** [comment]
At the moment we have 16 participants registered in person and 12 online. I expect most sessions to take the form of round table discussions, with on-site attendees sitting relatively close to each other around the modular tables offered by the venue.  Attendees will often want to present what they have on their screen to the rest of the group.

Here is a description of the video set-up I am planning on using in the main room of the venue. We'll have:
* a laptop dedicated to online streaming (personal hardware that I will bring with me)
* an LCD monitor connected to it (65" / 165cm) (rented from the venue)
* an EMEET Meeting Capsule connected to the streaming laptop (bought for the occasion)
* an EMEET M3 microphone/speaker daisy-chained to the meeting capsule (also bought for the meeting)

The presenting laptop would be connected to the Zoom meeting as a participant and showing Zoom on the LCD monitor. The EMEET devices are designed to work together and provide suitable conference audio for a video call with up to 25 people in a room.

To present something on the screen, participants will need to join the Zoom meeting on their computer (even if they are present on-site) and use the screen sharing functionality there.

For each session, we would have a dedicated on-site volunteer who would join the Zoom meeting from their own computer with Zoom host permissions. They would be a different person than the session facilitator. They would be responsible for:
* making sure interventions (raised hands, comments in the chat) from the remote participants are brought to the attention of the in-person participants
* muting and un-muting Zoom participants as needed
* tweaking video settings via the remote control of the meeting capsule, depending on what's happening in the session (switching between different video modes to take the best fit)

As an online attendee, one would be able to:
* see and hear people in the venue and online
* be heard and seen in the venue and online
* see whatever is being presented from a participant's screen
* also do screen sharing themselves

As an in-person attendee, one would be able to interact with online participants without having to pass a mic around, be able to easily see what's being shared on the screen.

I'm planning to test this set up with friends to understand if the tech works as I expect: if not, we can consider other solutions.

**Comment by wetneb** [comment]
I have tested the video set-up and it seems to work appropriately.
