### ISSUE TITLE
Plan social activities on the side

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/BarCamp2024#7]
It would be good to have an offering of some social activities we could do on the side of the event, so as not to be stuck in the same room doing intense work all the time. The goal is that people are able to get to know each other personally too.

We should find ideas of things to do not too far from the venue / proposed accommodation, which would likely appeal to as many people as possible in the group.

**Comment by ayushrai206** [comment]
I have an idea which is inspired from Outreachy's 1000 intern celebration's icebreaker activity, in which we were given a questionaire form to complete which required us to interact with each other, the questionaire consisted of questions like-
1)Identify and write the name of someone among the people present who has shifted careers to this field
2)Identify and write the name of someone who is in this field for over 20 years 
3)Identify and write the name of someone who is a design/documentation contributor
4)Identify and write the name of someone who is a parent...etc

**Comment by ayushrai206** [comment]
We can also have puzzles related to OpenRefine where people can team up in pairs.

**Comment by wetneb** [comment]
@ayushrai206 I like your idea above! Do you know if they came up with the list of questions with the knowledge of which attendee fits a particular description, or just make a list of "generic" questions?

**Comment by ayushrai206** [comment]
My first intuition was that it was generic but considering that there were questions where only 1/2 attendees could be approached as a fit, it could be the mix of both!

**Comment by wetneb** [comment]
In the evenings, I would propose something like this:
* Monday evening: go to a Biergarten where the UEFA Euro 2024 men's football matches are broadcast. I think this can be a fun place to hang out and get to know each other, even for people who are not into football at all (like me). I expect there will be a lot of places offering such viewings: see for instance [this list](https://rausgegangen.de/en/blog/european%20football%20championship-public-viewing-berlin/). We could pick one and tell people to meet there. I wouldn't book anything, just go for a large place. The matches are: 18:00 Belgium - Slovakia, 21:00 Austria - France. Perhaps that would be a good time to do the icebreaker @ayushrai206?
* Tuesday evening: we could book a table at a restaurant. I could pick a restaurant, circulate a form for people to sign up for that separately.
* Wednesday evening: if people still want to meet up after the end of the event, we could do that spontaneously, but I wouldn't prepare anything in particular.

In all evenings people would pay their own way, it wouldn't be covered by OpenRefine.

**Comment by magdmartin** [comment]
For Monday night, [prater-biergarten](https://www.prater-biergarten.de/de/geschichte/) is within a walkable distance from Tuechtig

**Comment by wetneb** [comment]
The program is agreed on
